version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db-test'
      PMA_USER: 'root'
      PMA_PASSWORD: 'password'
    ports:
    - '127.0.0.1:8080:80'